import type {Metadata} from "next";


export const metadata: Metadata = {
    title: "ContactsLayout - Create Next App",
    // description: "Generated by create next app",
};

type Props = { children: React.ReactNode; };
const ContactsLayout = ({children}: Props) => {
    return (
        <>
            {children}
        </>

    );
}
export default ContactsLayout;
