import type {Metadata} from "next";


export const metadata: Metadata = {
    title: "CarsLayout",
    // description: "Generated by create next app",
};

type Props = { children: React.ReactNode; };
const CarsLayout = ({children}: Props) => {
    return (
        <>
            {children}
        </>

    );
}
export default CarsLayout;